### ISSUE TITLE
TypeError: langs[(("../../lang/" + (intermediate value)) + ".json")] is not a function

### ISSUE THREAD

**Issue by parth391** [EugeneMeles/laravel-react-i18n#1]
Version:
Laravel: 9.29.0
inertiajs/inertia: 0.11.0
inertiajs/inertia-react: 0.8.1

My code

    createInertiaApp({
        title: (title) => ...,
        resolve(name) {...},
        setup({ el, App, props }) {
            return render(
                <LaravelReactI18nProvider
                  lang={'en'}
                  fallbackLang={'en'}
                  resolve={async (lang) => {
                    const langs = import.meta.glob('../../lang/*.json')
                    return await langs[`../../lang/${lang}.json`]()
                }}>
                    <App {...props} />
                </LaravelReactI18nProvider>,
            el);
        },
    });

Error

    TypeError: langs[(("../../lang/" + (intermediate value)) + ".json")] is not a function

**Comment by parth391** [comment]
@EugeneMeles can please help with this.

Also i am getting issue with [ssr](https://github.com/EugeneMeles/laravel-react-i18n/issues/2#issue-1375645404).

**Comment by EugeneMeles** [comment]
Wrap await langs to `try-catch`

    resolve={async (lang) => {
          const langs = import.meta.glob('../../lang/*.json')
          try {
              return await langs[`../../lang/${lang}.json`]()
          } catch (e) {
              //
          }
      }}

**Comment by parth391** [comment]
Thankyou
