### ISSUE TITLE
TypeError: i18n is not a function

### ISSUE THREAD

**Issue by parth391** [EugeneMeles/laravel-react-i18n#11]
With the laravel new release [v10.2.0](https://github.com/laravel/laravel/releases/tag/v10.2.0), i am getting below error,

    failed to load config from /.../example-app/vite.config.js
    error when starting dev server:
    TypeError: i18n is not a function
        at file:///.../example-app/vite.config.js.timestamp-1684327641779-1aba7c854728e.mjs:14:5
        at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

**Comment by EugeneMeles** [comment]
Is this error still in version 2.0.3(laravel-react-i18n) after update?

**Comment by parth391** [comment]
Yes, this error comes after adding `"type": "module",` to `package.json`.

**Comment by a-hussien** [comment]
I'm facing same issue.
# Error:
`
failed to load config from E:\laragon\www\multilang-react-demo\vite.config.js
error when starting dev server:
TypeError: i18n is not a function
    at file:///E:/laragon/www/multilang-react-demo/vite.config.js.timestamp-1684411850947-c0d2197e09094.mjs:13:5
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
`
- node v18.16.0
- npm v9.6.6

**Comment by EugeneMeles** [comment]
Fix update to latest version.
