### ISSUE TITLE
Missing keySeparator prop

### ISSUE THREAD

**Issue by selenasimicqs** [EugeneMeles/laravel-react-i18n#13]
Hello, 

I started using laravel-react-i18n library for translation.
I try to use nested keys, but with no success.
`t('sidebarItems.sidebarItem1')`
Does this library  allows keys to be phrases (having `:`, `.`) ?

Thank you

**Comment by EugeneMeles** [comment]
Hi,

This library use same algorithm as in laravel.

**Using Short Keys**:
```php
<?php
 
// lang/en/messages.php
 
return [
    'welcome' => 'Welcome to our application!',
    'some_else' => [
        'nestedMessage' => 'Nested Message',
    ],
];
```
```js
t('messages.welcome'); // Welcome to our application!

t('messages.some_else.nestedMessage'); // Nested Message
```

**Using Translation Strings As Keys**:
```js
// lang/nl.json
 
{
    "I love programming.": "Me encanta programar."
}
```
```js
t('I love programming.'); // Me encanta programar.
```
more info at [Localization](https://laravel.com/docs/10.x/localization)

**Comment by EugeneMeles** [comment]
The provider does not directly request `*.php` files.
You need to run preprocessing `i18n()` with vite-builder in vite.config.js.
```js
import i18n from 'laravel-react-i18n/vite'; // <-- add this

export default defineConfig({
    plugins: [
        laravel([
            'resources/css/app.css',
            'resources/js/app.js'
        ]),
        react(),
        i18n(), // <-- add this
    ],
});
```
```
/lang
    /uk
        messages.php
        validate.php
        helper.php
        user.php
```
After this step you receive transpiled php-translate(array) to json object and save it in lang folder as `/lang/php_uk.json`
and in `LaravelReactI18nProvider` `files` props receive only JSON file.
```js
      <LaravelReactI18nProvider
        files={import.meta.glob('/lang/*.json')}
      >
        <App {...props} />
      </LaravelReactI18nProvider>
```

You can use(part with composer & npm) [playground](https://github.com/EugeneMeles/laravel-react-i18n-playground#composer--npm) as example, this should be enough for front-end devs.

#### with this steps:
> in root dir of project:
1. `cd ./laravel/`
3. `npm install`
4. `npm run dev` or `npm run build`

**Comment by EugeneMeles** [comment]
Hi,

Yes it's correct behavior(deleting `php_*.json` in lang folder) after stop dev server or finished build.

In dev mode we need physical folder request(like as /lang/*).
But in produstion build, request goes to folder alias name(not true physical folder on server)
