### ISSUE TITLE
Text missing using Inertia SSR and Typescript

### ISSUE THREAD

**Issue by AlexanderFalkenberg** [EugeneMeles/laravel-react-i18n#25]
There is no text using the provided hook functions. There is some flicker if using: ` php artisan inertia:start-ssr`

Using the latest version of Inertia and Laravel 11

**Comment by wescopeland** [comment]
I am unable to reproduce this using the latest 1.x version of Inertia, Laravel 11, and React 18 with SSR. This is all currently deployed in prod.

Do you see any console errors in the browser or in the Inertia daemon?

**Comment by AlexanderFalkenberg** [comment]
Thank you, @wescopeland. I was not following the installation instructions correctly. I added the provider only to ssr.tsx instead of both to app.tsx and ssr.tsx. It was late. My bad. I'm closing this.
