### ISSUE TITLE
State got lost on language change 

### ISSUE THREAD

**Issue by parth391** [EugeneMeles/laravel-react-i18n#3]
https://user-images.githubusercontent.com/4966579/200322270-cb6de8ee-390c-4e86-ae63-c0117afc44c6.mov

My app.ts file

    import { LaravelReactI18nProvider } from 'laravel-react-i18n';

    createInertiaApp({
        ...
        setup({ el, App, props }) {
            const root = createRoot(el);
            root.render(
                <Provider store={store}>
                    <LaravelReactI18nProvider
                        lang={'en'}
                        fallbackLang={'en'}
                        resolve={async (lang) => {
                            const langs = import.meta.glob('/lang/*.json');
                            try {
                                return await langs[`/lang/${lang}.json`]();
                            } catch (e) {
                                //
                            }
                        }}>
                        <App {...props} />
                    </LaravelReactI18nProvider>
                </Provider>

            );
        },
    });

To set lang

    setLang(lang);

**Comment by EugeneMeles** [comment]
Hi @parth391 !
Please clarify, does your component `Provider` use React.Context store?

This may be because `authorization` is being re-rendered and store reset to default. It may be necessary to take its(auth store) outside of `LaravelReactI18nProvider` provider

**Comment by EugeneMeles** [comment]
Hi @parth391 !
Please clarify, does your component `Provider` use React.Context store?

This may be because `authorization` is being re-rendered and store reset to default. It may be necessary to take its(auth store) outside of `LaravelReactI18nProvider` provider

**Comment by parth391** [comment]
@EugeneMeles, I removed the store and auth process, but its going the same behaviour.

I have created a sample [repository](https://github.com/parth391/react-ssr-i18n).
On login page you can find the change lang button. On clicking, its redirecting me to the home page.

**Comment by parth391** [comment]
@EugeneMeles, 

https://user-images.githubusercontent.com/4966579/200644748-cd484d2e-47dc-4ff5-b5e8-94b93b90fb73.mov
