### ISSUE TITLE
Pre-rendering in SSR fails due to missing translation files

### ISSUE THREAD

**Issue by tommica** [EugeneMeles/laravel-react-i18n#5]
Thanks for making this project!

I'm using the libary with InertiaJS, and the translations work well when running `npm run dev` but after I run `npm run build` and `node bootstrap/ssr/ssr.mjs` the pre-rendering fails (`curl http://localhost`), but do work fine when testing it in the browser.

Code for the initialization:

```php
  createServer((page: any) =>
    createInertiaApp({
        page,
        render: ReactDOMServer.renderToString,
        title: (title) => `${title} - ${appName}`,
        resolve: (name) => import(`./Pages/${name}.tsx`),
        setup: ({App, props}) => {
            // @ts-ignore
            global.route = (name: any, params: any, absolute: any) =>
                route(name, params, absolute, {
                    ...page.props.ziggy,
                    location: new URL(page.props.ziggy.location),
                });

            // @ts-ignore
            return (
                <LaravelReactI18nProvider
                    lang={'da'}
                    fallbackLang={'en'}
                    resolve={async (lang) => {
                        const langs = import.meta.globEager("../../lang/*.json")
                        const fn = langs[`../../lang/${lang}.json`];

                        if (typeof fn === 'function') {
                            return await fn();
                        }
                    }
                    }>
                    <App {...props} />
                </LaravelReactI18nProvider>
            )
        },
    })
```

I'm not sure if I am doing something wrong, or it this is a bug, but I think the issue is on my side, because the translations work when using the page itself.

Initially I thought it was because the php_en.json file was not in the lang (as it is only there during the build process), but that was not the case, because that would mean the translations would not work at all after building the project.

**Comment by EugeneMeles** [comment]
Update to latest(2.0.0) version
